# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'MyListOfProductsCleanArchitecture'

#Networking Module
def networking_pods
  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireImage', '~> 4.1'
end

target 'Networking' do
  project 'Networking/Networking.project'
  networking_pods
end

target 'NetworkingTests' do
  project 'Networking/Networking.project'
  networking_pods
end

target 'Domain' do
  project 'Domain/Domain.project'
end

target 'MyListOfProductsCleanArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyListOfProductsCleanArchitecture
  networking_pods
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'RxDataSources', '~> 5.0'

end

target 'MyListOfProductsCleanArchitectureTests' do
    pod 'RxBlocking', '6.2.0'
    pod 'RxTest', '6.2.0'
end

target 'MyListOfProductsCleanArchitectureUITests' do
  # Pods for testing
end


